Semaine5/Jour1/UserModelSession/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/reponse', to: 'static_pages#reponse'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
	resources :users

end

Semaine5/Jour1/UserModelSession/app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates :pseudo,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  class << self

    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest,  User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

Semaine5/Jour1/UserModelSession/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

Semaine5/Jour1/UserModelSession/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:notice] = "User = #{user.id} Session user = #{session[:user_id]}"
      redirect_to user
    else
      # Create an error message.
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end

  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end

end

Semaine5/Jour1/UserModelSession/app/controllers/static_pages_controller.rb
require 'pry'

class StaticPagesController < ApplicationController
  def home
    p @current_user
  end

  def reponse
    if !logged_in?
      flash[:warning] = "Il faut se connecter avant"
      redirect_to :back
    end
  end
end

Semaine5/Jour1/UserModelSession/app/controllers/users_controller.rb
require 'pry'

class UsersController < ApplicationController

  before_action :get_user, only: [:show, :edit, :update, :delete, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @title = "New user bee"
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    @user.save
    redirect_to users_path
  end

  def update
    @user = User.update(params_user)
  end

  def edit
  end

  def destroy
    @user.destroy
  end

  def delete
  end

  private
    def params_user
      params.require(:user).permit(:pseudo,:email,:password,:password_confirmation)
    end

    def get_user
      @user = User.find(params[:id])
    end
end

Semaine5/Jour1/UserModelSession/app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end


  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

    # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end


  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

    # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end


end

Semaine5/Jour1/UserModelSession/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Semaine5/Jour1/UserModelSession/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
 <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="/">Home</a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Index</a>
      </li>
      <li>
        <%= if logged_in?
          link_to "Reponse1", '/reponse' , class: "nav-link"
          end %>
      </li>
      <li class="nav-item">
        <%= if logged_in?
          link_to "Logout1", '/logout', method: :delete, class: "nav-link", data: { confirm: "T'es sûr de toi ?" }
         else
           link_to "Login", '/login', class: "nav-link"
         end %>
      </li>
    </ul>
  </div>
</nav>

</header>

Semaine5/Jour1/UserModelSession/app/views/layouts/_headers.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

Semaine5/Jour1/UserModelSession/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= @title %></title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="container" style= " color: red; padding-top: 1.5cm " >
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>

  </body>
</html>

Semaine5/Jour1/UserModelSession/app/views/users/index.html.erb
<div class="container">
  <h2>Listing users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Pseudo</th>
        <th>Email</th>
        <th>Show</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.pseudo %></td>
        <td><%= user.email %></td>
       <td><%= link_to 'Show', user_path(user) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

Semaine5/Jour1/UserModelSession/app/views/users/new.html.erb
<div class="container">
<h1>Sign up</h1>
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :PseudoX %>
      <%= f.text_field :pseudo %>
      </br>
      <%= f.label :emailX %>
      <%= f.email_field :email %>
      </br>

      <%= f.label :passwordX %>
      <%= f.password_field :password %>
      </br>

      <%= f.label :password_confirmationX, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      </br>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

Semaine5/Jour1/UserModelSession/app/views/users/show.html.erb
<div class="container">
  <h2>Show user</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Pseudo</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @user.pseudo %></td>
        <td><%= @user.email %></td>
       <td><%= link_to 'Edit', edit_user_path(@user) %></td>
      </tr>
    </tbody>
  </table>
</div>