Semaine6/Jour2/project-gossips/config/routes.rb
Rails.application.routes.draw do
  resources :gossips
  devise_for :moussaillons

  root "gossips#index"

  get 'home/index'

  get 'home/private'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Semaine6/Jour2/project-gossips/app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :moussaillon

  validates :moussaillon, presence: true

end

Semaine6/Jour2/project-gossips/app/models/moussaillon.rb
class Moussaillon < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :gossips
end

Semaine6/Jour2/project-gossips/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up){ |u| u.permit(:email, :password, :password_confirmation, :anonymous_username) }
  end

end

Semaine6/Jour2/project-gossips/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: [:show, :edit, :update, :destroy]

  # GET /gossips
  # GET /gossips.json
  def index
    @gossips = Gossip.all
    # binding.pry
  end

  # GET /gossips/1
  # GET /gossips/1.json
  def show
  end

  # GET /gossips/new
  def new
    @gossip = Gossip.new
    # binding.pry
  end

  # GET /gossips/1/edit
  def edit
  end

  # POST /gossips
  # POST /gossips.json
  def create
    @gossip = Gossip.new(gossip_params)
    @gossip.moussaillon = current_moussaillon

    respond_to do |format|
      if @gossip.save
        format.html { redirect_to gossips_path, notice: 'Gossip was successfully created.' }
        format.json { render :show, status: :created, location: @gossip }
      else
        format.html { render :new }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gossips/1
  # PATCH/PUT /gossips/1.json
  def update
    respond_to do |format|
      if @gossip.update(gossip_params)
        format.html { redirect_to gossips_path, notice: 'Gossip was successfully updated.' }
        format.json { render :show, status: :ok, location: @gossip }
      else
        format.html { render :edit }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gossips/1
  # DELETE /gossips/1.json
  def destroy
    @gossip.destroy
    respond_to do |format|
      format.html { redirect_to gossips_url, notice: 'Gossip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gossip
      @gossip = Gossip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gossip_params
      params.require(:gossip).permit(:moussaillon_id, :content)
    end
end

Semaine6/Jour2/project-gossips/app/controllers/home_controller.rb
require 'pry'

class HomeController < ApplicationController

  def index
  end

  def private
  end

  def home
    binding.pry
    if  params.key?(:q)

    else
      redirect_to gossips_path
    end
  end
end

Semaine6/Jour2/project-gossips/app/helpers/gossips_helper.rb
module GossipsHelper
end

Semaine6/Jour2/project-gossips/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectGossips</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <p class="notice"> <%= notice %> </p>
    <p class="alert"> <%= alert %> </p>

    <%= yield %>

    <%= debug moussaillon_signed_in? %>
    Rails Env : <%= debug Rails.env %>
    <%= debug Rails.application.config.action_mailer.default_url_options %>
    <% if moussaillon_signed_in? %>
      Connectéxxx <%= current_moussaillon.email %>
      <%= link_to 'Se déconnecter', destroy_moussaillon_session_path, method: :delete %>
      <%= link_to 'Créer gossip', new_gossip_path %>
      <%= debug current_moussaillon.anonymous_username %>
    <% else %>
      Non connecté
      <%= link_to 'Se connecter', new_moussaillon_session_path %>
    <% end %>
  </body>
</html>